"""Knowledge about Salesforce standard objects the adapter can reuse instead of creating custom ones."""

KIND_TO_OBJECT = {
    "account": "Account",
    "contact": "Contact",
    "lead": "Lead",
    "opportunity": "Opportunity",
    "case": "Case",
    "product": "Product2",
    "quote": "Quote",
    "order": "Order",
    "contract": "Contract",
    "campaign": "Campaign",
    "task": "Task",
    "event": "Event",
}

# Custom fields for Task/Event live on the shared Activity object.
FIELD_HOST = {"Task": "Activity", "Event": "Activity"}

# canonical field key -> standard field API name
STANDARD_FIELDS: dict[str, dict[str, str]] = {
    "Account": {
        "account_name": "Name",
        "company_name": "Name",
        "phone": "Phone",
        "website": "Website",
        "industry": "Industry",
        "annual_revenue": "AnnualRevenue",
        "number_of_employees": "NumberOfEmployees",
        "employees": "NumberOfEmployees",
        "description": "Description",
        "type": "Type",
        "account_type": "Type",
        "billing_street": "BillingStreet",
        "billing_city": "BillingCity",
        "billing_state": "BillingState",
        "billing_postal_code": "BillingPostalCode",
        "billing_country": "BillingCountry",
        "city": "BillingCity",
        "state": "BillingState",
        "country": "BillingCountry",
        "postal_code": "BillingPostalCode",
        "address": "BillingStreet",
        "account_number": "AccountNumber",
        "fax": "Fax",
        "rating": "Rating",
    },
    "Contact": {
        "first_name": "FirstName",
        "last_name": "LastName",
        "email": "Email",
        "phone": "Phone",
        "mobile": "MobilePhone",
        "mobile_phone": "MobilePhone",
        "title": "Title",
        "job_title": "Title",
        "designation": "Title",
        "department": "Department",
        "birthdate": "Birthdate",
        "date_of_birth": "Birthdate",
        "lead_source": "LeadSource",
        "mailing_street": "MailingStreet",
        "mailing_city": "MailingCity",
        "city": "MailingCity",
        "state": "MailingState",
        "country": "MailingCountry",
        "postal_code": "MailingPostalCode",
        "address": "MailingStreet",
        "description": "Description",
        "salutation": "Salutation",
    },
    "Lead": {
        "first_name": "FirstName",
        "last_name": "LastName",
        "company": "Company",
        "company_name": "Company",
        "email": "Email",
        "phone": "Phone",
        "mobile": "MobilePhone",
        "mobile_phone": "MobilePhone",
        "title": "Title",
        "status": "Status",
        "lead_status": "Status",
        "lead_source": "LeadSource",
        "source": "LeadSource",
        "industry": "Industry",
        "rating": "Rating",
        "website": "Website",
        "city": "City",
        "state": "State",
        "country": "Country",
        "postal_code": "PostalCode",
        "street": "Street",
        "address": "Street",
        "annual_revenue": "AnnualRevenue",
        "number_of_employees": "NumberOfEmployees",
        "description": "Description",
    },
    "Opportunity": {
        "opportunity_name": "Name",
        "deal_name": "Name",
        "amount": "Amount",
        "deal_value": "Amount",
        "close_date": "CloseDate",
        "expected_close_date": "CloseDate",
        "stage": "StageName",
        "probability": "Probability",
        "type": "Type",
        "lead_source": "LeadSource",
        "next_step": "NextStep",
        "description": "Description",
    },
    "Case": {
        "subject": "Subject",
        "description": "Description",
        "status": "Status",
        "priority": "Priority",
        "origin": "Origin",
        "case_origin": "Origin",
        "type": "Type",
        "reason": "Reason",
    },
    "Product2": {
        "product_name": "Name",
        "product_code": "ProductCode",
        "code": "ProductCode",
        "sku": "StockKeepingUnit",
        "description": "Description",
        "family": "Family",
        "product_family": "Family",
        "category": "Family",
        "is_active": "IsActive",
        "active": "IsActive",
    },
    "Campaign": {
        "campaign_name": "Name",
        "status": "Status",
        "type": "Type",
        "start_date": "StartDate",
        "end_date": "EndDate",
        "budgeted_cost": "BudgetedCost",
        "budget": "BudgetedCost",
        "actual_cost": "ActualCost",
        "expected_revenue": "ExpectedRevenue",
        "description": "Description",
        "is_active": "IsActive",
    },
    "Order": {
        "status": "Status",
        "effective_date": "EffectiveDate",
        "order_date": "EffectiveDate",
        "description": "Description",
    },
    "Contract": {
        "status": "Status",
        "start_date": "StartDate",
        "contract_term": "ContractTerm",
        "term_months": "ContractTerm",
        "description": "Description",
    },
    "Quote": {
        "quote_name": "Name",
        "status": "Status",
        "expiration_date": "ExpirationDate",
        "description": "Description",
    },
    "Task": {
        "subject": "Subject",
        "due_date": "ActivityDate",
        "status": "Status",
        "priority": "Priority",
        "description": "Description",
        "comments": "Description",
    },
    "Event": {
        "subject": "Subject",
        "start": "StartDateTime",
        "start_date_time": "StartDateTime",
        "end": "EndDateTime",
        "end_date_time": "EndDateTime",
        "location": "Location",
        "description": "Description",
    },
}

# child object -> parent object -> standard lookup field
STANDARD_LOOKUPS: dict[str, dict[str, str]] = {
    "Account": {"Account": "ParentId"},
    "Contact": {"Account": "AccountId", "Contact": "ReportsToId"},
    "Opportunity": {"Account": "AccountId", "Campaign": "CampaignId", "Contact": "ContactId"},
    "Case": {"Account": "AccountId", "Contact": "ContactId"},
    "Order": {"Account": "AccountId", "Contract": "ContractId", "Opportunity": "OpportunityId"},
    "Contract": {"Account": "AccountId"},
    "Quote": {"Opportunity": "OpportunityId", "Account": "AccountId", "Contact": "ContactId"},
    "Campaign": {"Campaign": "ParentId"},
}

# Stage field + value set per standard object whose lifecycle is a StandardValueSet.
STAGE_VALUE_SETS = {
    "Opportunity": ("StageName", "OpportunityStage"),
    "Lead": ("Status", "LeadStatus"),
    "Case": ("Status", "CaseStatus"),
}

# Standard objects that may be the master in a master-detail relationship.
MASTER_CAPABLE = {"Account", "Contact", "Opportunity", "Case", "Contract", "Campaign", "Order"}

IMPLICIT_FIELDS = {
    "name": "Name",
    "owner": "OwnerId",
    "created_date": "CreatedDate",
    "last_modified_date": "LastModifiedDate",
    "created_by": "CreatedById",
    "id": "Id",
}

# Objects whose name is a compound (no single Name field to write in flows / imports).
COMPOUND_NAME = {"Contact": ["FirstName", "LastName"], "Lead": ["FirstName", "LastName", "Company"]}
