"""in-app llm settings

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-28 12:57:56.730122
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_credentials",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("api_key_encrypted", sa.Text(), nullable=True),
        sa.Column("key_hint", sa.String(length=12), nullable=True),
        sa.Column("model", sa.String(length=120), nullable=True),
        sa.Column("effort", sa.String(length=16), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "provider"),
    )
    with op.batch_alter_table("llm_credentials", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_llm_credentials_org_id"), ["org_id"], unique=False)

    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("llm_provider", sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.drop_column("llm_provider")

    with op.batch_alter_table("llm_credentials", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_llm_credentials_org_id"))

    op.drop_table("llm_credentials")
    # ### end Alembic commands ###
