"""Platform-neutral Solution Design Document (Markdown) for client sign-off."""

from app.domain.business_model import BusinessModel, FieldType
from app.domain.validation import Issue


def _esc(text: str | None) -> str:
    return (text or "").replace("|", "\\|").replace("\n", " ")


def render_design_doc(
    model: BusinessModel,
    project_name: str,
    version: int,
    summary: str,
    issues: list[Issue],
    open_questions: list[dict],
    llm_usage: dict | None = None,
) -> str:
    p = model.profile
    out = [f"# Solution Design: {project_name}", ""]
    provider = (llm_usage or {}).get("provider")
    if provider == "mock":
        out += [
            "> **Draft generated without AI (offline demo mode).** It mirrors spreadsheet columns only and",
            "> does not reflect the business. Configure an AI provider and re-analyse before sharing.",
            "",
        ]
    generated = f", generated by {llm_usage['model']}" if llm_usage and llm_usage.get("model") else ""
    source = generated if provider != "mock" else ""
    out += [f"*Design version {version}{source or (', edited manually' if llm_usage is None else '')}*", ""]
    if summary:
        out += ["## Summary", "", summary, ""]

    out += [
        "## Business profile",
        "",
        "| | |",
        "|---|---|",
        f"| Client | {_esc(p.name)} |",
        f"| Industry | {_esc(p.industry)}" + (f" / {_esc(p.sub_industry)}" if p.sub_industry else "") + " |",
        f"| Sales model | {p.sales_model} |",
        f"| Revenue models | {', '.join(p.revenue_models) or '-'} |",
        f"| Regions | {', '.join(p.regions) or '-'} |",
        f"| Currencies | {', '.join(p.currencies) or '-'} |",
        f"| CRM users | {p.crm_user_count or '-'} |",
        f"| Compliance | {', '.join(p.compliance) or '-'} |",
        "",
        p.description,
        "",
    ]
    for title, items in (("Goals", p.goals), ("Pain points", p.pain_points), ("Out of scope", p.out_of_scope)):
        if items:
            out += [f"### {title}", ""] + [f"- {i}" for i in items] + [""]

    out += ["## Data model", ""]
    for e in model.entities:
        out += [f"### {e.label} (`{e.key}`, {e.kind})", "", e.description or "", ""]
        out += ["| Field | Type | Required | Notes |", "|---|---|---|---|"]
        for f in e.fields:
            notes = []
            if f.type == FieldType.lookup:
                notes.append(f"{f.relationship or 'lookup'} to `{f.reference_entity}`")
            if f.options:
                notes.append(
                    "values: " + ", ".join(o.label for o in f.options[:15]) + (" ..." if len(f.options) > 15 else "")
                )
            if f.unique:
                notes.append("unique")
            if f.pii:
                notes.append("PII")
            if f.description:
                notes.append(f.description)
            out.append(f"| {_esc(f.label)} | {f.type} | {'yes' if f.required else ''} | {_esc('; '.join(notes))} |")
        out.append("")

    if model.processes:
        out += ["## Processes", ""]
        for pr in model.processes:
            out += [
                f"### {pr.name}",
                "",
                pr.description or "",
                "",
                " -> ".join(f"{s.label}" + (f" ({s.category})" if s.category != "open" else "") for s in pr.stages),
                "",
            ]

    if model.automations:
        out += ["## Automations", "", "| Automation | Entity | Trigger | Actions |", "|---|---|---|---|"]
        for a in model.automations:
            cond = (
                f" when {a.condition_logic} of: "
                + ", ".join(f"{c.field} {c.operator} {c.value or ''}".strip() for c in a.conditions)
                if a.conditions
                else ""
            )
            actions = "; ".join(x.description for x in a.actions)
            out.append(f"| {_esc(a.name)} | {a.entity} | {a.trigger.type}{_esc(cond)} | {_esc(actions)} |")
        out.append("")

    if model.roles:
        out += ["## Roles and access", ""]
        for r in model.roles:
            head = f"### {r.label}" + (f" (reports to `{r.reports_to}`)" if r.reports_to else "")
            out += [
                head,
                "",
                r.description or "",
                "",
                "| Entity | Read | Create | Edit | Delete | View all |",
                "|---|---|---|---|---|---|",
            ]
            for pm in r.permissions:
                marks = ["x" if v else "" for v in (pm.read, pm.create, pm.edit, pm.delete, pm.view_all)]
                out.append(f"| {pm.entity} | " + " | ".join(marks) + " |")
            out.append("")

    if model.integrations:
        out += [
            "## Integrations",
            "",
            "| System | Direction | Frequency | Entities | Purpose |",
            "|---|---|---|---|---|",
        ]
        for i in model.integrations:
            out.append(
                f"| {_esc(i.system)} | {i.direction} | {i.frequency} | {', '.join(i.entities)} | "
                f"{_esc(i.description)} |"
            )
        out.append("")

    if model.reports:
        out += ["## Reports and dashboards", ""]
        out += [
            f"- **{r.name}** on {r.entity}"
            + (f", grouped by {', '.join(r.group_by)}" if r.group_by else "")
            + (f", metrics: {', '.join(r.metrics)}" if r.metrics else "")
            for r in model.reports
        ]
        out.append("")

    if model.data_mappings:
        out += ["## Data migration mapping", "", "| Source | Column | Target | Transform |", "|---|---|---|---|"]
        for m in model.data_mappings:
            out.append(f"| {_esc(m.source)} | {_esc(m.column)} | {m.entity}.{m.field} | {_esc(m.transform)} |")
        out.append("")

    if model.assumptions:
        out += (
            ["## Assumptions", ""]
            + [f"- {a.statement}" + (f" ({a.rationale})" if a.rationale else "") for a in model.assumptions]
            + [""]
        )
    if open_questions:
        out += ["## Open questions", ""] + [f"- **[{q['priority']}]** {q['text']}" for q in open_questions] + [""]
    warnings = [i for i in issues if i.severity != "info"]
    if warnings:
        out += ["## Validation notes", ""] + [f"- {i.severity}: {i.message}" for i in warnings] + [""]
    return "\n".join(out)
